# Generated by Django 5.0.1 on 2024-01-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_prospect_alter_followupreport_prospect'),
        ('user', '0002_remove_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prospect',
        ),
    ]
