# Generated by Django 5.0.1 on 2024-01-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_contact_user_no_of_followup_user_no_of_wins_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
    ]
