# Generated by Django 5.0.1 on 2024-02-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.BigIntegerField()),
                ('whatsapp', models.BigIntegerField()),
                ('receipt', models.FileField(upload_to='customers_receipt/')),
                ('other_files', models.FileField(upload_to='other_customers_files/')),
                ('amount', models.BigIntegerField()),
                ('payment_status', models.CharField(choices=[('completed', 'COMPLETED'), ('incompleted', 'INCOMPLETED')], max_length=250)),
                ('follow_up_description', models.TextField()),
                ('area_of_interest', models.CharField(blank=True, choices=[('Land', 'LAND'), ('Housing', 'HOUSING'), ('membership', 'MEMBERSHIP'), ('partnership', 'PARTNERSHIP'), ('others', 'OTHERS')], max_length=20, null=True)),
                ('other_info', models.CharField(max_length=250)),
                ('planned_commitment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_means', models.CharField(blank=True, choices=[('WhatsApp', 'whatsApp'), ('Phone Call', 'phone call'), ('Email', 'email'), ('Physical Visitation', 'physical visitation'), ('Chat', 'chat'), ('Others', 'others')], max_length=250, null=True)),
                ('other_means', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('additional_comment', models.TextField()),
                ('media', models.FileField(upload_to='report_media')),
                ('remark', models.CharField(max_length=250)),
                ('customer_feedback', models.CharField(max_length=250)),
                ('action_plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('hour_spent', models.TimeField()),
                ('followup_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PropectContactSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PropectSocialHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('other_property_type', models.CharField(max_length=250)),
                ('media1', models.FileField(upload_to='property_media')),
                ('media2', models.FileField(upload_to='property_media')),
                ('media3', models.FileField(upload_to='property_media')),
                ('media4', models.FileField(upload_to='property_media')),
            ],
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.BigIntegerField()),
                ('phone_number2', models.BigIntegerField(blank=True, null=True)),
                ('whatsapp', models.BigIntegerField()),
                ('status', models.CharField(blank=True, choices=[('propect', 'Propect'), ('open', 'Open'), ('working', 'Working'), ('meeting_set', 'Meeting Set'), ('opportunity', 'Opportunity'), ('opportunity_lost', 'Opportunity Lost'), ('customer', 'Customer'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('pending_approval', 'Pending Approval'), ('awaiting_feedback', 'Awaiting Feedback'), ('contact_attempted', 'Contact Attempted'), ('contract_sent', 'Contract Sent'), ('negotiation', 'Negotiation'), ('contract_signed', 'Contract Signed'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('pending_verification', 'Pending Verification'), ('scheduled_for_visit', 'Scheduled for Visit'), ('follow_up_needed', 'Follow-up Needed'), ('other', 'Other')], default='propect', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProspectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ReportFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
