# Generated by Django 5.0.1 on 2024-01-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_means', models.CharField(blank=True, choices=[('WhatsApp', 'whatsApp'), ('Phone Call', 'phone call'), ('Email', 'email')], max_length=250, null=True)),
                ('other_means', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='report_media')),
                ('remark', models.CharField(max_length=250)),
                ('action_plan', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='property_media')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
