# Generated by Django 5.0.1 on 2024-01-19 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreport',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.prospect'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
        migrations.AddField(
            model_name='property',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.propertymedia'),
        ),
        migrations.AddField(
            model_name='reportfeedback',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.followupreport'),
        ),
    ]
