# Generated by Django 5.0.1 on 2024-01-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='media',
        ),
        migrations.AddField(
            model_name='property',
            name='media1',
            field=models.FileField(default=0, upload_to='property_media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='media2',
            field=models.FileField(default=0, upload_to='property_media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='media3',
            field=models.FileField(default=0, upload_to='property_media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='media4',
            field=models.FileField(default=0, upload_to='property_media'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PropertyMedia',
        ),
    ]
