# Generated by Django 5.0.1 on 2024-02-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='address',
            field=models.CharField(max_length=400),
        ),
    ]
