# Generated by Django 5.0.1 on 2024-02-28 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='area_of_interest',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_source',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='facebook_username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='follow_up_marketer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='instagram_username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='other_info',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='planned_commitment_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='prefix',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='property',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='twitter_username',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='customer',
            name='prospect',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='property.prospect'),
            preserve_default=False,
        ),
    ]
