# Generated by Django 5.0.1 on 2024-04-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupreport',
            name='action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='additional_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='customer_feedback',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='followup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='hour_spent',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='report_media'),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='other_means',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='followupreport',
            name='remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(blank=True, choices=[('propect', 'Propect'), ('open', 'Open'), ('working', 'Working'), ('meeting_set', 'Meeting Set'), ('opportunity', 'Opportunity'), ('opportunity_lost', 'Opportunity Lost'), ('customer', 'Customer'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('pending_approval', 'Pending Approval'), ('awaiting_feedback', 'Awaiting Feedback'), ('contact_attempted', 'Contact Attempted'), ('contract_sent', 'Contract Sent'), ('negotiation', 'Negotiation'), ('contract_signed', 'Contract Signed'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('pending_verification', 'Pending Verification'), ('scheduled_for_visit', 'Scheduled for Visit'), ('follow_up_needed', 'Follow-up Needed'), ('others', 'Others')], default='propect', max_length=20, null=True),
        ),
    ]
