# Generated by Django 5.0.1 on 2024-01-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_property_media_property_media1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='other_property_type',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
