# Generated by Django 5.0.1 on 2024-01-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_prospect_alter_followupreport_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='prefix',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
