# Generated by Django 5.0.1 on 2024-01-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_prospect_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
