# Generated by Django 5.0.1 on 2024-01-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_prospect_follow_up_marketer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('pending_approval', 'Pending Approval'), ('awaiting_feedback', 'Awaiting Feedback'), ('contact_attempted', 'Contact Attempted'), ('contract_sent', 'Contract Sent'), ('negotiation', 'Negotiation'), ('contract_signed', 'Contract Signed'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('archived', 'Archived'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('pending_verification', 'Pending Verification'), ('scheduled_for_visit', 'Scheduled for Visit'), ('follow_up_needed', 'Follow-up Needed'), ('other', 'Other')], default='open', max_length=20, null=True),
        ),
    ]
