# Generated by Django 5.0.1 on 2024-01-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='follow_up_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='other_files',
            field=models.FileField(default=0, upload_to='other_customers_files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'COMPLETED'), ('incompleted', 'INCOMPLETED')], default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='receipt',
            field=models.FileField(default=0, upload_to='customers_receipt/'),
            preserve_default=False,
        ),
    ]
